### ISSUE TITLE
Question about CSS styling of the page

### ISSUE THREAD

**Issue by Jrmy-rbr** [bcrowell/inf#5]
Hello,

Is it OK if I work on adding CSS styling to this page?

I was thinking about doing something similar to SympyLive (https://live.sympy.org/) whose page is open source, so I can reuse some of their CSS.

If yes, I'd mostly add 1 or 2 CSS files, and change some small styling things in the `Terminal.js` and `index.html` files. No other files should be affected.

**Comment by bcrowell** [comment]
Is it basically cosmetic stuff that you have in mind? If so, then I'd be happy to see what you come up with, but I'd reserve the right not to use it if I don't prefer it to what I currently have.  Were you thinking of adding sidebars like on the SymPy page? That could be helpful. If you want to avoid the possibility of doing a lot of work that I would then not like, one possibility would be to do a mockup.

Since you've been actively contributing to the project, another possibility would be if you just do a friendly fork. I don't plan on doing any work on it myself in the future except for basic maintenance. If you wanted to do a friendly fork, I would just add a link saying, "Hey, here's a friendly fork which, unlike my original version, is actively maintained and being improved."

**Comment by Jrmy-rbr** [comment]
Yes, it is mostly cosmetics. I put below two screenshots about what I got so far.
I would still add some missing information in the footer, like the origin of the CSS files (ie the sympy repo) etc.  I might also move the text around, cause now there is some empty space in some places.

Let me know whether this style interests you, or whether you'd like to check the page in a browser, in which case I may try to push it into a branch, and you can play with it.

I'm fine with making a fork if you prefer keeping your version as is 😄 


Here is a screenshot the top page:
<img width="1440" alt="Screenshot 2023-01-03 at 17 51 46" src="https://user-images.githubusercontent.com/63064766/210403121-e839d866-42b0-4bf5-bd47-39b7bf413b83.png">


Here the bottom page:
<img width="1440" alt="Screenshot 2023-01-03 at 17 52 00" src="https://user-images.githubusercontent.com/63064766/210403141-971054cf-9dec-4782-992b-9462966b3383.png">

**Comment by bcrowell** [comment]
That looks really nice.

I would suggest that you just fork it. It's not that I don't like what you're doing -- quite the opposite. But it seems like you have some interest in working on the project, and I don't think I'm adding any value by being in the loop. All I'm going to do is suppress your enthusiam and slow you down.

**Comment by Jrmy-rbr** [comment]
Fair enough, I'll make a fork then 😄

**Comment by bcrowell** [comment]
Cool, have fun!

I added	a link from my project's README describing the fork and linking to it.

Looking	forward	to seeing what you do :-)

  Ben
